name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview
          toolchain: stable
          rustflags: ""

      - name: Install llvm-cov
        env:
          LLVM_COV_RELEASES: https://github.com/taiki-e/cargo-llvm-cov/releases
        run: |
          host=$(rustc -Vv | grep host | sed 's/host: //')
          curl -fsSL $LLVM_COV_RELEASES/latest/download/cargo-llvm-cov-$host.tar.gz | tar xzf - -C "$HOME/.cargo/bin"

      - name: Test and generate coverage report
        run: ./tests/coverage.sh --ci

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: coverage.lcov
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}
